<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class VocabularySeeder extends Seeder
{
    public function run(): void
    {
        $vocabularies = [
            // WORD - Difficulty 1 (Standard)
            [
                'word' => 'implement',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '実行する、実施する',
                'part_of_speech' => '動詞',
                'example_sentence' => 'We need to implement the new policy by next month.',
                'synonym' => 'execute, carry out',
                'antonym' => 'neglect, ignore',
                'frequency' => 85,
                'tags' => 'business,project',
            ],
            [
                'word' => 'deadline',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '締め切り、期限',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The deadline for the report is Friday.',
                'synonym' => 'due date, time limit',
                'antonym' => null,
                'frequency' => 92,
                'tags' => 'business,time',
            ],
            [
                'word' => 'budget',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '予算、経費',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The project exceeded its budget by 20%.',
                'synonym' => 'funds, allowance',
                'antonym' => null,
                'frequency' => 88,
                'tags' => 'business,finance',
            ],
            [
                'word' => 'collaborate',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '協力する、共同で行う',
                'part_of_speech' => '動詞',
                'example_sentence' => 'Our team will collaborate with the marketing department.',
                'synonym' => 'cooperate, work together',
                'antonym' => 'compete',
                'frequency' => 78,
                'tags' => 'business,teamwork',
            ],
            [
                'word' => 'revenue',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '収益、収入',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The company reported record revenue this quarter.',
                'synonym' => 'income, earnings',
                'antonym' => 'expense, cost',
                'frequency' => 82,
                'tags' => 'business,finance',
            ],
            [
                'word' => 'negotiate',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '交渉する',
                'part_of_speech' => '動詞',
                'example_sentence' => 'We need to negotiate the terms of the contract.',
                'synonym' => 'discuss, bargain',
                'antonym' => null,
                'frequency' => 75,
                'tags' => 'business,communication',
            ],
            [
                'word' => 'efficient',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '効率的な',
                'part_of_speech' => '形容詞',
                'example_sentence' => 'The new system is more efficient than the old one.',
                'synonym' => 'effective, productive',
                'antonym' => 'inefficient, wasteful',
                'frequency' => 80,
                'tags' => 'business,productivity',
            ],
            [
                'word' => 'schedule',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '予定、スケジュール',
                'part_of_speech' => '名詞',
                'example_sentence' => 'Please check your schedule for availability.',
                'synonym' => 'timetable, plan',
                'antonym' => null,
                'frequency' => 90,
                'tags' => 'business,time',
            ],
            [
                'word' => 'proposal',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '提案、企画書',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The proposal was approved by the board.',
                'synonym' => 'suggestion, plan',
                'antonym' => null,
                'frequency' => 77,
                'tags' => 'business,document',
            ],
            [
                'word' => 'merchandise',
                'type' => 'WORD',
                'difficulty' => 1,
                'meaning' => '商品、製品',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The store received new merchandise yesterday.',
                'synonym' => 'goods, products',
                'antonym' => null,
                'frequency' => 72,
                'tags' => 'business,retail',
            ],

            // WORD - Difficulty 2 (Hard)
            [
                'word' => 'acquisition',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '買収、取得',
                'part_of_speech' => '名詞',
                'example_sentence' => 'The acquisition of the startup was completed last week.',
                'synonym' => 'purchase, takeover',
                'antonym' => 'sale, divestiture',
                'frequency' => 65,
                'tags' => 'business,corporate',
            ],
            [
                'word' => 'stipulate',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '規定する、明記する',
                'part_of_speech' => '動詞',
                'example_sentence' => 'The contract stipulates a 30-day notice period.',
                'synonym' => 'specify, require',
                'antonym' => null,
                'frequency' => 55,
                'tags' => 'business,legal',
            ],
            [
                'word' => 'consolidate',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '統合する、強化する',
                'part_of_speech' => '動詞',
                'example_sentence' => 'The company decided to consolidate its operations.',
                'synonym' => 'merge, combine',
                'antonym' => 'separate, divide',
                'frequency' => 60,
                'tags' => 'business,corporate',
            ],
            [
                'word' => 'leverage',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '活用する、てこ入れする',
                'part_of_speech' => '動詞',
                'example_sentence' => 'We should leverage our existing customer base.',
                'synonym' => 'utilize, exploit',
                'antonym' => 'waste, neglect',
                'frequency' => 68,
                'tags' => 'business,strategy',
            ],
            [
                'word' => 'mitigate',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '軽減する、緩和する',
                'part_of_speech' => '動詞',
                'example_sentence' => 'We need to mitigate the risks associated with this project.',
                'synonym' => 'reduce, lessen',
                'antonym' => 'aggravate, worsen',
                'frequency' => 58,
                'tags' => 'business,risk',
            ],
            [
                'word' => 'scrutinize',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '精査する、詳しく調べる',
                'part_of_speech' => '動詞',
                'example_sentence' => 'The auditors will scrutinize the financial records.',
                'synonym' => 'examine, inspect',
                'antonym' => 'ignore, overlook',
                'frequency' => 52,
                'tags' => 'business,audit',
            ],
            [
                'word' => 'reimbursement',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '払い戻し、弁償',
                'part_of_speech' => '名詞',
                'example_sentence' => 'Please submit your receipts for reimbursement.',
                'synonym' => 'refund, compensation',
                'antonym' => null,
                'frequency' => 62,
                'tags' => 'business,finance',
            ],
            [
                'word' => 'contingency',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '不測の事態、緊急時対応',
                'part_of_speech' => '名詞',
                'example_sentence' => 'We have a contingency plan in case of emergencies.',
                'synonym' => 'emergency, backup',
                'antonym' => null,
                'frequency' => 56,
                'tags' => 'business,planning',
            ],
            [
                'word' => 'proprietary',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '専有の、独自の',
                'part_of_speech' => '形容詞',
                'example_sentence' => 'This is proprietary software developed in-house.',
                'synonym' => 'exclusive, private',
                'antonym' => 'public, open',
                'frequency' => 54,
                'tags' => 'business,technology',
            ],
            [
                'word' => 'unprecedented',
                'type' => 'WORD',
                'difficulty' => 2,
                'meaning' => '前例のない',
                'part_of_speech' => '形容詞',
                'example_sentence' => 'The company achieved unprecedented growth this year.',
                'synonym' => 'unparalleled, unmatched',
                'antonym' => 'common, typical',
                'frequency' => 64,
                'tags' => 'business,general',
            ],

            // IDIOM - Difficulty 1 (Standard)
            [
                'word' => 'on the same page',
                'type' => 'IDIOM',
                'difficulty' => 1,
                'meaning' => '同じ認識を持っている、意見が一致している',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'Let\'s make sure we\'re all on the same page before the meeting.',
                'synonym' => 'in agreement',
                'antonym' => 'at odds',
                'frequency' => 75,
                'tags' => 'business,communication',
            ],
            [
                'word' => 'get the ball rolling',
                'type' => 'IDIOM',
                'difficulty' => 1,
                'meaning' => '物事を始める、開始する',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'Let\'s get the ball rolling on this project.',
                'synonym' => 'start, begin',
                'antonym' => 'halt, stop',
                'frequency' => 70,
                'tags' => 'business,action',
            ],
            [
                'word' => 'touch base',
                'type' => 'IDIOM',
                'difficulty' => 1,
                'meaning' => '連絡を取る、確認する',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'I\'ll touch base with you next week.',
                'synonym' => 'contact, reach out',
                'antonym' => null,
                'frequency' => 78,
                'tags' => 'business,communication',
            ],
            [
                'word' => 'keep someone in the loop',
                'type' => 'IDIOM',
                'difficulty' => 1,
                'meaning' => '情報を共有する、状況を伝える',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'Please keep me in the loop about any changes.',
                'synonym' => 'inform, update',
                'antonym' => 'exclude',
                'frequency' => 72,
                'tags' => 'business,communication',
            ],
            [
                'word' => 'call it a day',
                'type' => 'IDIOM',
                'difficulty' => 1,
                'meaning' => '仕事を切り上げる、終わりにする',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'We\'ve worked hard enough. Let\'s call it a day.',
                'synonym' => 'finish, stop',
                'antonym' => 'continue',
                'frequency' => 68,
                'tags' => 'business,work',
            ],

            // IDIOM - Difficulty 2 (Hard)
            [
                'word' => 'cut corners',
                'type' => 'IDIOM',
                'difficulty' => 2,
                'meaning' => '手抜きをする、経費を節約する',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'We can\'t cut corners on quality.',
                'synonym' => 'economize, take shortcuts',
                'antonym' => 'be thorough',
                'frequency' => 62,
                'tags' => 'business,quality',
            ],
            [
                'word' => 'back to the drawing board',
                'type' => 'IDIOM',
                'difficulty' => 2,
                'meaning' => '最初からやり直す',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'The plan failed, so it\'s back to the drawing board.',
                'synonym' => 'start over',
                'antonym' => 'proceed',
                'frequency' => 58,
                'tags' => 'business,planning',
            ],
            [
                'word' => 'bring to the table',
                'type' => 'IDIOM',
                'difficulty' => 2,
                'meaning' => '（議論に）提供する、貢献する',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'What skills do you bring to the table?',
                'synonym' => 'offer, contribute',
                'antonym' => null,
                'frequency' => 65,
                'tags' => 'business,negotiation',
            ],
            [
                'word' => 'go the extra mile',
                'type' => 'IDIOM',
                'difficulty' => 2,
                'meaning' => '期待以上のことをする',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'Our team always goes the extra mile for clients.',
                'synonym' => 'exceed expectations',
                'antonym' => 'do the minimum',
                'frequency' => 60,
                'tags' => 'business,service',
            ],
            [
                'word' => 'think outside the box',
                'type' => 'IDIOM',
                'difficulty' => 2,
                'meaning' => '型にはまらない考え方をする',
                'part_of_speech' => 'イディオム',
                'example_sentence' => 'We need to think outside the box to solve this problem.',
                'synonym' => 'be creative, innovate',
                'antonym' => 'follow convention',
                'frequency' => 66,
                'tags' => 'business,creativity',
            ],
        ];

        foreach ($vocabularies as $vocab) {
            Vocabulary::updateOrCreate(
                ['word' => $vocab['word']],
                $vocab
            );
        }
    }
}
